# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enviarmails.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Notas(object):
    def setupUi(self, Notas):
        Notas.setObjectName("Notas")
        Notas.resize(302, 294)
        Notas.setStyleSheet("*{\n"
"font-family:century gothic;\n"
"color:white;\n"
"}\n"
"\n"
"QDialog{\n"
"background:  rgba(2, 14, 38, 255)\n"
"\n"
"}\n"
"\n"
"QFrame\n"
"{\n"
"background: #020E26;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QToolButton\n"
"{\n"
"background: #2d89ef;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QToolButton:hover\n"
"{\n"
"background:  #2b5797;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QLabel{\n"
"color:white;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"background:#1d1d1d;\n"
"border:none;\n"
"border-bottom: 1px solid white;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"background: #2d89ef;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #2b5797;\n"
"color: white;\n"
"border-radius: 5px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QGroupBox{\n"
"color:white;\n"
"\n"
"}\n"
"\n"
"QGroupBox#ref{\n"
"color:white;\n"
"}\n"
"\n"
"QLabel#Titulo\n"
"{\n"
"font-size:20px;\n"
"}\n"
"QTableWidget\n"
"{\n"
"color:white;\n"
"text-align:center;\n"
"}\n"
"")
        self.Titulo = QtWidgets.QLabel(Notas)
        self.Titulo.setGeometry(QtCore.QRect(40, 20, 191, 21))
        self.Titulo.setObjectName("Titulo")
        self.l_desc = QtWidgets.QLabel(Notas)
        self.l_desc.setGeometry(QtCore.QRect(40, 60, 211, 31))
        self.l_desc.setObjectName("l_desc")
        self.frame = QtWidgets.QFrame(Notas)
        self.frame.setGeometry(QtCore.QRect(30, 110, 171, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.cb_tp = QtWidgets.QCheckBox(self.frame)
        self.cb_tp.setGeometry(QtCore.QRect(20, 100, 121, 17))
        self.cb_tp.setObjectName("cb_tp")
        self.cb_1 = QtWidgets.QCheckBox(self.frame)
        self.cb_1.setGeometry(QtCore.QRect(20, 10, 101, 16))
        self.cb_1.setObjectName("cb_1")
        self.cb_3 = QtWidgets.QCheckBox(self.frame)
        self.cb_3.setGeometry(QtCore.QRect(20, 70, 121, 17))
        self.cb_3.setObjectName("cb_3")
        self.cb_2 = QtWidgets.QCheckBox(self.frame)
        self.cb_2.setGeometry(QtCore.QRect(20, 40, 111, 17))
        self.cb_2.setObjectName("cb_2")
        self.pushButton = QtWidgets.QPushButton(Notas)
        self.pushButton.setGeometry(QtCore.QRect(60, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Notas)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 250, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Notas)
        QtCore.QMetaObject.connectSlotsByName(Notas)

    def retranslateUi(self, Notas):
        _translate = QtCore.QCoreApplication.translate
        Notas.setWindowTitle(_translate("Notas", "Dialog"))
        self.Titulo.setText(_translate("Notas", "Enviar notas"))
        self.l_desc.setText(_translate("Notas", "¿Que notas desea enviar?"))
        self.cb_tp.setText(_translate("Notas", "Parcial 4"))
        self.cb_1.setText(_translate("Notas", "Parcial 1"))
        self.cb_3.setText(_translate("Notas", "Parcial 3"))
        self.cb_2.setText(_translate("Notas", "Parcial 2"))
        self.pushButton.setText(_translate("Notas", "Enviar"))
        self.pushButton_2.setText(_translate("Notas", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Notas = QtWidgets.QDialog()
    ui = Ui_Notas()
    ui.setupUi(Notas)
    Notas.show()
    sys.exit(app.exec_())
