# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 602)
        MainWindow.setStyleSheet("*{\n"
"font-family:century gothic;\n"
"}\n"
"\n"
"QMainWindow{\n"
"background: qlineargradient(spread:pad, x1:1, y1:0.739, x2:1, y2:0.25, stop:0 rgba(2, 14, 38, 255), stop:1 rgba(167, 189, 217, 255))\n"
"\n"
"}\n"
"\n"
"QFrame\n"
"{\n"
"background: #020E26;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QToolButton\n"
"{\n"
"background: #2d89ef;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QToolButton:hover\n"
"{\n"
"background:  #2b5797;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QLabel{\n"
"color:white;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"background:#1d1d1d;\n"
"border:none;\n"
"border-bottom: 1px solid white;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"background: #2d89ef;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #2b5797;\n"
"color: white;\n"
"border-radius: 5px;\n"
"font-weight:bold;\n"
"}\n"
"\n"
"QGroupBox{\n"
"color:white;\n"
"\n"
"}\n"
"\n"
"QGroupBox#ref{\n"
"color:white;\n"
"}\n"
"\n"
"QLabel#Titulo\n"
"{\n"
"font-size:20px;\n"
"}\n"
"QTableWidget\n"
"{\n"
"color:white;\n"
"text-align:center;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 30, 761, 481))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Titulo = QtWidgets.QLabel(self.frame)
        self.Titulo.setGeometry(QtCore.QRect(50, 20, 591, 41))
        self.Titulo.setObjectName("Titulo")
        self.T_main = QtWidgets.QTableWidget(self.frame)
        self.T_main.setGeometry(QtCore.QRect(20, 100, 721, 361))
        self.T_main.setObjectName("T_main")
        self.T_main.setColumnCount(7)
        self.T_main.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.T_main.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_main.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_main.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_main.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_main.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_main.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_main.setHorizontalHeaderItem(6, item)
        self.l_curso = QtWidgets.QLabel(self.frame)
        self.l_curso.setGeometry(QtCore.QRect(50, 60, 47, 13))
        self.l_curso.setObjectName("l_curso")
        self.l_alumnos = QtWidgets.QLabel(self.frame)
        self.l_alumnos.setGeometry(QtCore.QRect(370, 60, 151, 16))
        self.l_alumnos.setObjectName("l_alumnos")
        self.b_mails = QtWidgets.QPushButton(self.centralwidget)
        self.b_mails.setGeometry(QtCore.QRect(200, 520, 75, 23))
        self.b_mails.setObjectName("b_mails")
        self.b_certif = QtWidgets.QPushButton(self.centralwidget)
        self.b_certif.setGeometry(QtCore.QRect(330, 520, 131, 23))
        self.b_certif.setObjectName("b_certif")
        self.b_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.b_agregar.setGeometry(QtCore.QRect(490, 520, 131, 23))
        self.b_agregar.setObjectName("b_agregar")
        self.l_cell = QtWidgets.QLabel(self.centralwidget)
        self.l_cell.setGeometry(QtCore.QRect(60, 530, 47, 13))
        self.l_cell.setText("")
        self.l_cell.setObjectName("l_cell")
        self.b_eliminar = QtWidgets.QPushButton(self.centralwidget)
        self.b_eliminar.setGeometry(QtCore.QRect(630, 520, 131, 23))
        self.b_eliminar.setObjectName("b_eliminar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titulo.setText(_translate("MainWindow", "Seguimiento del curso"))
        item = self.T_main.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Alumno"))
        item = self.T_main.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mail"))
        item = self.T_main.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Parcial 1"))
        item = self.T_main.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Parcial 2"))
        item = self.T_main.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Parcial 3"))
        item = self.T_main.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "TP"))
        item = self.T_main.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Certificado"))
        self.l_curso.setText(_translate("MainWindow", "Curso:"))
        self.l_alumnos.setText(_translate("MainWindow", "Alumnos:"))
        self.b_mails.setText(_translate("MainWindow", "Enviar mails"))
        self.b_certif.setText(_translate("MainWindow", "Entregar certificados"))
        self.b_agregar.setText(_translate("MainWindow", "Agregar alumno"))
        self.b_eliminar.setText(_translate("MainWindow", "Eliminar alumno"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
